[Issue#13] Add Jupyter start commands

diff --git a/bin/helium b/bin/helium
--- a/bin/helium
+++ b/bin/helium
@@ -15,7 +15,7 @@ IRODS_CWD="/commonsshareZone/home"
 IRODS_ZONE_NAME="commonsshareZone"
 
 usage() {
-    echo "Usage: $0 {build|run} [option...]"
+    echo "Usage: $0 {build|run} [options...]"
     echo
     echo "  build {base|jupyter|all}"
     echo "    Run command to build specified or all Docker images."
@@ -23,8 +23,17 @@ usage() {
     echo "  run {base|jupyter}"
     echo "    Specify image to run."
     echo "    base: "
+    echo "       -cwl | -toil     Required. Select which virtual environment to start."
+    echo "           -cwl         Starts virtual environment with Python 3 and CWLTool."
+    echo "           -toil        Starts virtual environment with Python 2.7 and Toil."
     echo "       -U|--username    Required. Username to connect to iRODS."
     echo "       -P|--password    Optional. Password to connect to iRODS."
+    echo
+    echo "    jupyter: "
+    echo "       -wes-server | -jupyter | -venv     Required. Select start option."
+    echo "           -wes-server          Starts WES server in Docker container."
+    echo "           -jupyter             Starts Jupyter notebook server in contianer."
+    echo "           -venv                Starts Jupyter notebook as background process."
     echo
 }
 build () {
@@ -46,13 +55,13 @@ run () {
     base () {
         local IRODS_USER_NAME=
         local IRODS_PASSWORD=
-        local VENV=
+        local START=
 
         while [ "$1" != "" ]; do
             case $1 in
-                -cwl )                   VENV="venv"
+                -cwl )                   START="venv"
                                         ;;
-                -toil )                  VENV="toilvenv"
+                -toil )                  START="toilvenv"
                                         ;;
                 -U | --user )           shift
                                         IRODS_USER_NAME=$1
@@ -80,32 +89,61 @@ run () {
                 -e IRODS_ZONE_NAME=${IRODS_ZONE_NAME}         \
                 -p 8888:8888 -p 90:80                         \
                 heliumdatacommons/datacommons-base            \
-                ${VENV}
+                ${START}
         else
             echo "ERROR: iRODS Username not provided."
             exit 1;
         fi
     }
+    #               heliumdatacommons/datacommons-jupyter         \
     jupyter () {
-        local tag=
-        for arg in $*; do
-	    case $arg in
-	        --latest*) tag=:latest; echo $tag;;
-	        *) echo "unknown command"; return 1;;
-	    esac
+        local IRODS_USER_NAME=
+        local IRODS_PASSWORD=
+        local START="jupyter"
+
+        while [ "$1" != "" ]; do
+            case $1 in
+                -wes-server )           START="wes-server"
+                                        ;;
+                -jupyter )              START="jupyter"
+                                        ;;
+                -venv )                 START="venv"
+                                        ;;
+                -U | --user )           shift
+                                        IRODS_USER_NAME=$1
+                                        ;;
+                -P | --password )       shift
+                                        IRODS_PASSWORD=$1
+                                        ;;
+                * )                     echo "ERROR: Input not found."
+                                        exit 1
+            esac
+            shift
         done
-        docker run -it --privileged --rm --name dc_jupyter   \
-               -e DATACOMMONS_CHRONOS_ENDPOINT=${CHRONOS}    \
-               -e DATACOMMONS_CHRONOS_PROTO=${CHRONOS_PROTO} \
-               -p 8888:8888 -p 90:80                         \
-               --volume ~/dev:/home/dockeruser/hdev            \
-               heliumdatacommons/datacommons-jupyter$tag         \
-               venv
+
+        if [ ! -z "$IRODS_USER_NAME" ]
+        then
+            docker run -it --privileged --rm --name dc_jupyter  \
+                -e DATACOMMONS_CHRONOS_ENDPOINT=${CHRONOS}      \
+                -e DATACOMMONS_CHRONOS_PROTO=${CHRONOS_PROTO}   \
+                -e IRODS_PORT=${IRODS_PORT}                     \
+                -e IRODS_HOST=${IRODS_HOST}                     \
+                -e IRODS_HOME=${IRODS_HOME}                     \
+                -e IRODS_CWD=${IRODS_CWD}                       \
+                -e IRODS_USER_NAME=${IRODS_USER_NAME}           \
+                -e IRODS_PASSWORD=${IRODS_PASSWORD}             \
+                -e IRODS_ZONE_NAME=${IRODS_ZONE_NAME}           \
+                -p 8888:8888 -p 90:80                           \
+                --volume ~/dev:/home/dockeruser/hdev            \
+                heliumdatacommons/datacommons-jupyter           \
+                ${START}
+        else
+            echo "ERROR: iRODS Username not provided."
+            exit 1;
+        fi
     }
     $*
 }
-
-#               heliumdatacommons/datacommons-jupyter         \
 
 
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
